name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: test build
      uses: actions/checkout@v2
    - name: test build
      uses: ./.github/actions/arduino
      with:
        run-command: ".ci/build.sh"
