on: [push]

jobs:
  learn_githubactions_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: learn githubactions
      id: hello
      uses: actions/checkout@v2
    # Use the output from the `hello` step
    - name: Get the output time
      run: |
          docker build . --file Dockerfile --target test -t techmasat:uwr_arduino
          docker container run techmasat:uwr_arduino